global:
  environment: production

backend:
  name: backend
  replicaCount: 2
  image:
    repository: githubsurveillance-backend
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 3001
  resources:
    limits:
      cpu: 200m
      memory: 384Mi
    requests:
      cpu: 100m
      memory: 256Mi
  env:
    GITHUB_TOKEN: ""
    GITHUB_ORG: "amvirdev"
  ingress:
    enabled: true
    className: alb
    host: api.githubsurveillance.local

frontend:
  name: frontend
  replicaCount: 1
  image:
    repository: githubsurveillance-frontend
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 3002
  resources:
    limits:
      cpu: 150m
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 128Mi
  env:
    REACT_APP_API_URL: "http://api.githubsurveillance.local"
  ingress:
    enabled: true
    className: alb
    host: githubsurveillance.local
