backend:
  imagePullSecrets:
    - name: github-registry-secret
  image:
    repository: amvirdev/github-surveillance-backend
    pullPolicy: Always
  replicaCount: 1
  resources:
    limits:
      cpu: 500m
      memory: 1024Mi
    requests:
      cpu: 200m
      memory: 512Mi
  ingress:
    enabled: true
    className: alb
    annotations:
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: ip
      alb.ingress.kubernetes.io/target-group-attributes: stickiness.enabled=true,stickiness.type=lb_cookie
      alb.ingress.kubernetes.io/target-group-port: '3001'
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
      alb.ingress.kubernetes.io/healthcheck-port: '3001'
      alb.ingress.kubernetes.io/healthcheck-path: /
      alb.ingress.kubernetes.io/backend-protocol: HTTP
      alb.ingress.kubernetes.io/target-group-port: '3001'
    rules:
      - http:
          paths:
            - path: /
              pathType: Prefix
              backend:
                service:
                  name: github-surveillance-backend
                  port:
                    number: 3001

frontend:
  imagePullSecrets:
    - name: github-registry-secret
  image:
    repository: amvirdev/github-surveillance-frontend
    pullPolicy: Always
  replicaCount: 1
  resources:
    limits:
      cpu: 300m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi
  env:
    REACT_APP_API_URL: "http://api.githubsurveillance.basic-eks.local"
  ingress:
    enabled: true
    className: alb
    annotations:
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: ip
      alb.ingress.kubernetes.io/target-group-attributes: stickiness.enabled=true,stickiness.type=lb_cookie
      alb.ingress.kubernetes.io/target-group-port: '3002'
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
      alb.ingress.kubernetes.io/healthcheck-port: '3002'
      alb.ingress.kubernetes.io/healthcheck-path: /
      alb.ingress.kubernetes.io/backend-protocol: HTTP
      alb.ingress.kubernetes.io/target-group-port: '3002'
    rules:
      - http:
          paths:
            - path: /
              pathType: Prefix
              backend:
                service:
                  name: github-surveillance-frontend
                  port:
                    number: 3002