apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: github-surveillance-frontend
  description: React frontend for GitHub surveillance application
  annotations:
    backstage.io/kubernetes-id: basic-eks
    backstage.io/kubernetes-namespace: github-surveillance
    backstage.io/kubernetes-label-selector: app=github-surveillance-frontend
    github.com/project-slug: enginuity-io/github-surveillance
    backstage.io/techdocs-ref: dir:.
    docker.io/image: enginuity-io/github-surveillance-frontend:v1.0.1
    backstage.io/managed-by-location: url:https://github.com/enginuity-io/github-surveillance
    backstage.io/managed-by-origin-location: url:https://github.com/enginuity-io/github-surveillance
    github.com/security-insights: 'enabled'
  tags:
    - react
    - web
    - javascript
    - frontend
spec:
  type: website
  lifecycle: production
  owner: platform-engineering
  system: github-surveillance
  providesApis:
    - github-surveillance-web-api
  dependsOn:
    - component:github-surveillance-backend
    - api:github-surveillance-web-api
    - component:basic-eks
    - component:nodegroup-ng-1
    - component:nodegroup-managed-ng
    - component:nodegroup-basic-nodegroup
    - resource:github-surveillance-namespace
