apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: basic-eks
  description: AWS EKS Cluster for GitHub Surveillance application
  annotations:
    backstage.io/kubernetes-id: basic-eks
    github.com/project-slug: enginuity-io/github-surveillance
    backstage.io/techdocs-ref: dir:.
  tags:
    - aws
    - eks
    - kubernetes
    - infrastructure
spec:
  type: kubernetes-cluster
  lifecycle: production
  owner: platform-engineering
  system: github-surveillance
  dependsOn: []
